### ISSUE TITLE
Why FeedRegistry is not in the main repo?

### ISSUE THREAD

**Issue by aelmanaa** [smartcontractkit/feed-registry#13]
Hi there,

- Was looking for the implementation of [FeedRegistry.sol](https://github.com/smartcontractkit/feed-registry/blob/master/contracts/FeedRegistry.sol) and finally found it here :) why is it not put under the main [chainlink repo](https://github.com/smartcontractkit/chainlink) like it's done for FeedRegistryInterface ?
- Is it planned to deploy FeedRegistry in other chains?  I see that it is only deployed in ETH Mainnet & Kovan (cf. [docs](https://docs.chain.link/docs/feed-registry/#contract-addresses) ) 
thanks a lot

**Comment by yosriady** [comment]
> Hi there,
> 
> - Was looking for the implementation of [FeedRegistry.sol](https://github.com/smartcontractkit/feed-registry/blob/master/contracts/FeedRegistry.sol) and finally found it here :) why is it not put under the main [chainlink repo](https://github.com/smartcontractkit/chainlink) like it's done for FeedRegistryInterface ?
> - Is it planned to deploy FeedRegistry in other chains?  I see that it is only deployed in ETH Mainnet & Kovan (cf. [docs](https://docs.chain.link/docs/feed-registry/#contract-addresses) ) 
> thanks a lot

The feed registry was experimental and therefore was not part of the main report.

Currently no plans to deploy it on other chains.
